[package]
name = "kafka-test"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
clap_derive = "4.5.3"

rdkafka = { version = "0.36.2", features = ["default", "cmake-build"] }
tokio = { version = "1.39.2", features = ["full"] }
